<?php

/**
 * @file
 * Provides Hipay payment method for Drupal Commerce.
 */

/**
 * Implements hook_permission().
 */
function commerce_hipay_permission() {
  return array(
    'administer hipay' => array(
      'title' => t('Administer Hipay'),
      'description' => t('Perform administrative actions with Hipay.'),
    ),
  );
}

/**
 * Returns a list of currencies enabled on the site.
 *
 * @return array
 *   An array of currencies enabled on the site.
 */
function commerce_hipay_get_enabled_currencies() {
  $currencies = array();

  foreach (commerce_currencies(TRUE) as $currency_code => $currency) {
    $currencies[$currency_code] = t('@code - !name', array(
      '@code' => $currency['code'],
      '!name' => $currency['name'],
    ));
    if (!empty($currency['symbol'])) {
      $currencies[$currency_code] .= ' - ' . check_plain($currency['symbol']);
    }
  }

  return $currencies;
}

/**
 * Returns a list of locale identifiers supported by Hipay gateway.
 *
 * @return array
 *   An array of locale identifiers supported by Hipay gateway.
 */
function commerce_hipay_get_supported_languages() {
  return array(
    'fr_FR' => t('French / France'),
    'fr_BE' => t('French / Belgium'),
    'en_GB' => t('English / Great Britain'),
    'en_US' => t('English / United States'),
    'es_ES' => t('Spanish / Spain'),
    'de_DE' => t('Deutsch / Germany'),
    'pt_PT' => t('Portuguese / Portugal'),
    'pt_BR' => t('Portuguese / Brazil'),
    'nl_NL' => t('Dutch / Holland'),
    'nl_BE' => t('Dutch / Belgium'),
  );
}

/**
 * Returns a list of currencies supported by Hipay gateway.
 *
 * @return array
 *   An array of currencies supported by Hipay gateway.
 */
function commerce_hipay_get_supported_currencies() {
  return array(
    'EUR' => t('Euro'),
    'CAD' => t('Canadian dollar'),
    'USD' => t('United States dollar'),
    'CHF' => t('Swiss franc'),
    'AUD' => t('Australian dollar'),
    'GBP' => t('British pound'),
    'SEK' => t('Swedish krona'),
    'BRL' => t('Brazilian real'),
  );
}
